### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by strivedreams23** [dc42/DuetWiFiSocketServer#3]
I am building a project to enable me to modify the firmware for the Duet3d wifi.
My plan is to repurpose some pins to add an extra motor control.
I have been following the build instructions for MacOS

So far I have CoreNG, FreeRTOS and RRFLibraries all compiling without errors.
I added the DuetWiFiSocketServer which threw errors.. then added CoreESP8266 and LwipESP8266
which are also throwing errors.. 

Apparently I am missing 
xtensa-lx106-elf-g++ 
and 
xtensa-lx106-elf-gcc
should I have those already?

where do I get them from?

**Comment by dc42** [comment]
Use Google to find a download, there are several.
